# Generated by Django 2.2 on 2021-01-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, default='image_placeholder.jpg', null=True, upload_to='category/'),
        ),
    ]
