# Generated by Django 2.2 on 2021-02-18 21:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#28a745', max_length=18),
        ),
    ]
